name: piemonte-data-scraper

# Schedule the run
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: Scrape data
    # Set the type of machine to run on
    runs-on: macos-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Prepare Selenium
      - name: Prepare Selenium
        # https://github.com/marketplace/actions/setup-chromedriver
        uses: nanasess/setup-chromedriver@master
      # Launch browser
      - name: Launch browser
        run: |
          google-chrome --version
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless
      # Get data
      - name: Get data
        run: |
          python scarica_dati_da_regione_piemonte.py
      # Commit & Push
      - name: Commit a new report (if necessary)
        run: |
          echo "Checking data on: `date`"
          if cmp -s data/staging-covid-piemonte.csv data/covid-piemonte.csv ; then
            echo "No changes to commit";
          else
            echo "New update available";
            cp data/{metadata.txt,covid-piemonte.csv} data/previous/
            mv data/staging-covid-piemonte.csv data/covid-piemonte.csv
            mv data/staging-metadata.txt data/metadata.txt
            git config --global user.name 'Covid Piemonte Bot'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -am "Refresh data on: `date`"
            git push
          fi
        env:
          TZ: Europe/Rome
